image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - dockerize

build_job: 
  image: node
  stage: build
  tags:
    - pokemonFront
  
  script: 
    - echo "start building app"
    - npm install
    - npm build
    - echo "build succesfull"

test_job: 
  image: node
  stage: test
  tags:
    - pokemonFront
  script:
    - echo "test app"
    - npm install
    - npm test
    - echo "tests succesfull"

dockeriz_job:
  image: docker:latest
  stage: dockerize
  tags:
    - docker

  services:
    - docker:dind

  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  
  script:
    - echo "start building image..."
    - docker build -t rikdegoede/pokemon-card-market-front .
    - echo "pushing image..."
    - docker push rikdegoede/pokemon-card-market-front