image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - dockerize

dockeriz_job:
  image: docker:latest
  stage: dockerize
  tags:
    - docker

  services:
    - docker:dind

  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  
  script:
    - echo "start building container..."
    - docker build -t rikdegoede/pokemon-card-market-front
    - echo "pushing container..."
    - docker push rikdegoede/pokemon-card-market-front